spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgres://localhost:5432/test
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 9090
